/// The `delivery` gate — whether the implementer's claim is well formed.
///
/// It checks **coverage and shape, never truth**, exactly as `requisition
/// check` "judges presence, not quality". It cannot tell whether the evidence a
/// row names is honest; what catches that is the person who writes the
/// verification, and that is not a weakness of the gate — it is where the
/// signature was placed on purpose (ADR 0008 §6).
///
/// The same shape runs again at `dod check`, over `verification.md`. It is not
/// a duplicated rule: here it is the implementer's **claim** that a criterion
/// is covered, there it is the verifier's **judgement** that it holds. Two
/// documents, two acts.
library;

class DeliveryViolation {
  final String code;
  final String message;

  const DeliveryViolation(this.code, this.message);

  @override
  String toString() => '$code: $message';
}

class DeliveryGateResult {
  final List<DeliveryViolation> violations;

  const DeliveryGateResult(this.violations);

  bool get passed => violations.isEmpty;
}

class DeliveryGate {
  const DeliveryGate();

  /// Judges [deliveryMd] against the [criteria] the contract declares and the
  /// [prTitle] recorded beside it.
  ///
  /// The criteria come from the caller rather than from a document read here:
  /// they are generated by `SpecificationGate.acIds`, so the contract, the
  /// delivery and the verification cannot disagree about what a criterion is
  /// called.
  DeliveryGateResult evaluate(
    String deliveryMd, {
    required List<String> criteria,
    required String? prTitle,
  }) {
    final violations = <DeliveryViolation>[];

    _checkPrTitle(prTitle, violations);
    _checkCoverage(deliveryMd, criteria, violations);

    return DeliveryGateResult(violations);
  }

  // ─── Rules ──────────────────────────────────────────────────────────────

  /// `type(scope)!: subject` — shape only.
  ///
  /// No closed list of types: that would be this gate deciding what kinds of
  /// change a project is allowed to make. What it enforces is that the title
  /// parses, because the title is the sentence that reaches whoever reads the
  /// history and it is written once, at the end, when nobody is looking at it.
  void _checkPrTitle(String? prTitle, List<DeliveryViolation> violations) {
    if (prTitle == null || prTitle.trim().isEmpty) {
      violations.add(const DeliveryViolation(
        'DELIVERY_PR_TITLE_MISSING',
        'No pull-request title — add `pr_title` to state.yaml. It is a commit '
            'message, so it is English and Conventional Commits in every '
            'project.',
      ));
      return;
    }

    if (!_conventionalCommit.hasMatch(prTitle.trim())) {
      violations.add(DeliveryViolation(
        'DELIVERY_PR_TITLE_MALFORMED',
        '`pr_title` is not Conventional Commits: "$prTitle". It reads '
            '`type(scope)!: subject`, where the scope and the `!` are optional.',
      ));
    }
  }

  static final _conventionalCommit =
      RegExp(r'^[a-z][a-z0-9]*(\([^)]+\))?!?: *\S.*$');

  /// Every criterion the contract declares is named, and each names something
  /// a reader can open or run.
  void _checkCoverage(
    String deliveryMd,
    List<String> criteria,
    List<DeliveryViolation> violations,
  ) {
    if (criteria.isEmpty) {
      violations.add(const DeliveryViolation(
        'DELIVERY_NO_CRITERIA',
        'The contract declares no acceptance criterion, so there is nothing '
            'this delivery could claim. Check the specification first.',
      ));
      return;
    }

    final rows = _evidenceByCriterion(deliveryMd);

    final unclaimed = criteria.where((id) => !rows.containsKey(id)).toList();
    if (unclaimed.isNotEmpty) {
      violations.add(DeliveryViolation(
        'DELIVERY_AC_UNCLAIMED',
        'The contract declares criteria this delivery does not mention: '
            '${unclaimed.join(', ')}. A criterion you could not meet belongs in '
            '"What was not done", not left out.',
      ));
    }

    final empty = criteria
        .where((id) => rows.containsKey(id) && !_isFilled(rows[id]!))
        .toList();
    if (empty.isNotEmpty) {
      violations.add(DeliveryViolation(
        'DELIVERY_AC_NO_EVIDENCE',
        'Named with nowhere to look: ${empty.join(', ')}. The row exists to '
            'save the reader the search — a test name, a file and line, or a '
            'command.',
      ));
    }
  }

  // ─── Parsing ────────────────────────────────────────────────────────────

  /// The evidence cell of every `| id | evidence |` row, by criterion id.
  Map<String, String> _evidenceByCriterion(String md) {
    final rows = <String, String>{};
    for (final line in md.split('\n')) {
      if (!line.trimLeft().startsWith('|')) continue;
      final cells = _cells(line);
      if (cells.length < 2) continue;
      if (!_criterionId.hasMatch(cells[0])) continue; // header, separator, prose
      rows[cells[0]] = cells[1];
    }
    return rows;
  }

  static final _criterionId = RegExp(r'^US\d+-AC\d+$');

  List<String> _cells(String row) => row
      .trim()
      .replaceAll(RegExp(r'^\||\|$'), '')
      .split('|')
      .map((c) => c.trim())
      .toList();

  /// A cell is filled when something real survives removing the template's own
  /// comments — the same test the specification gate applies to its rows.
  bool _isFilled(String value) => value
      .replaceAll(RegExp(r'<!--.*?-->', dotAll: true), '')
      .replaceAll(RegExp(r'[.\s]+$'), '')
      .trim()
      .isNotEmpty;
}
